erDiagram
    UTILISATEUR {
        int id_utilisateur PK
        varchar nom
        varchar email
        enum role
    }
    PANIER {
        int id_panier PK
        int id_utilisateur FK
        datetime date_mise_a_jour
    }
    ELEMENT_PANIER {
        int id_element_panier PK
        int id_panier FK
        enum type_element
        int id_element_ref
        int quantite
        decimal prix_unitaire
        datetime date_ajout
    }
    FAVORI {
        int id_favori PK
        int id_utilisateur FK
        enum type_element
        int id_element_ref
        datetime date_ajout
    }
    AVIS {
        int id_avis PK
        int id_utilisateur FK
        enum type_cible
        int id_cible
        int note
        text commentaire
        datetime date_avis
    }
    VOYAGEUR_SEJOUR {
        int id PK
        int id_reservation FK
        int id_utilisateur FK
        varchar refe_sejour
        datetime date_ajout
    }

    UTILISATEUR ||--|| PANIER : "possede (1,1)"
    PANIER ||--o{ ELEMENT_PANIER : "contient (1,N)"
    UTILISATEUR ||--o{ FAVORI : "enregistre (1,N)"
    UTILISATEUR ||--o{ AVIS : "redige (1,N)"
    UTILISATEUR ||--o{ VOYAGEUR_SEJOUR : "participe (1,N)"
